name: Github Actions Practice
on: [push]
jobs:
  Explore-Github-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "El flujo de trabajo ha sido ejecutado en el evento: ${{ github.event_name }}"
      - run: echo "El trabajo se est√° ejecutado en un servidor ${{ runner.os }} hospedado en Github"
      - run: echo "El nombre de la rama es: ${{ github.ref }} y tu repositorio es: ${{ github.repository }}."
      - name: Verificar el codigo del repositorio
        uses: actions/checkout@v2
      - run: echo "El repositorio: ${{ github.repository }} ha sido clonado al runner."
      - run: echo "El flujo de trabajo esta listo para verificar el codigo en el runner."
      - name: Listar archivos en el repositorio
        run: ls ${{ github.workspace }}
      - run: echo "El estado del trabajo es: ${{ job.status }}."
